services:
  - type: web
    name: diet-analysis-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: FLASK_ENV
        value: production
      - key: FIREBASE_PROJECT_ID
        value: nutri-scan-a-i-3am8a8
      - key: GOOGLE_API_KEY
        value: AIzaSyDVe2rzp7Kclm8cpQcOuz2siq-oZ7A0Dys
